### ISSUE TITLE
Error building missing "just-group-by"

### ISSUE THREAD

**Issue by pierroo** [staltz/react-native-emoji-modal#2]
Error: Unable to resolve module just-group-by/index.js 
=>  const groupBy = require('just-group-by/index.js');

**Comment by staltz** [comment]
Have you done npm install?

**Comment by pierroo** [comment]
when I am doing npm install to install your library, am I also supposed to run npm install from your library in node modules?

Or do you mean this library is actually meant to be copied locally as source of inspiration?

Because eventually this is what I did, and it does work well when the whole logic etc is copied locally.

regardless, good job on that one :)

**Comment by staltz** [comment]
`just-group-by` is a dependency in our library, so you probably just have a local problem with your npm install or yarn or pnpm or whatever: https://github.com/staltz/react-native-emoji-modal/blob/7eddb141633472008a57eb2553a23924e7407441/package.json#L15

**Comment by JeanDes-Code** [comment]
Hi, I just had same issue and I'm using Expo. 
I firstly installed the package while the app was running, and it worked.
Then when I restarted it, it failed at building time for iOS (I have not tried android).
I've deleted all node_modules and installed everything back again, but it keeps failing with the same error : 

> Unable to resolve "just-group-by/index.js" from "node_modules\react-native-emoji-modal\index.js"


It seems to be related to just-group-by package swapping from index.js to index.cjs in last version .. 
The same problem occurs with just-map-values.
I just added those two line in my package.json and it worked (later versions swapped .js to .cjs ): 
> "just-group-by": "2.1.2",
> "just-map-values": "3.1.1",

**Comment by staltz** [comment]
Oh so seems like we need version pinning because `just-*` libraries issued a breaking change on the patch number? :P

**Comment by JeanDes-Code** [comment]
I think updating your package dependencies to latest versions of those two packages is the best practice, and will work nicely but you could also just specify those specific versions here in your package.json 
> "just-group-by": "2.1.2",
> "just-map-values": "3.1.1",

(everything I said is based on their CHANGELOG.md files )

![image](https://user-images.githubusercontent.com/78590821/211410682-1448b091-02be-4cf3-ad35-0aa75fa1b034.png)

**Comment by staltz** [comment]
Version 0.2.3 released

Thanks y'all
